# Generated by Django 4.2.4 on 2023-08-25 13:41

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AlterField(
            model_name='eventorganizerproposal',
            name='banner',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='banner'),
        ),
        migrations.AlterField(
            model_name='eventorganizerproposal',
            name='proposal',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='proposals'),
        ),
    ]
