# Generated by Django 4.0.10 on 2023-08-25 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userticket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdata',
            name='ticket',
        ),
        migrations.AddField(
            model_name='userticket',
            name='sales_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.salesdata'),
        ),
    ]
